# Conclusion

In this project, we used data from the CDC and the US Census to analyze the relationship between demographic information and flu vaccination coverage in the United States. We also provided some insights into the influence of the COVID pandemic on flu vaccine coverage. 

We started with analyzing geographical patterns of flu vaccination coverage in 2021, the latest data we have. We used choropleth maps and found that the areas with high vaccine coverage are mainly in the Midwest, Northeast, and Mid-Atlantic regions of the United States, which may be caused by political history or climate variations between regions. Then we analyzed the time series data considering the nationwide flu vaccination coverage rate from 2009 to 2021, along with some chosen racial and age groups. We found that the general pattern of flu vaccination coverage is increasing with a dip in 2017. We also found there are certain patterns associated with racial groups and age groups, such as that children have the largest vaccination coverage, and that white racial group has the largest vaccination coverage. Disadvantaged groups might be disproportionately affected by the flu, as with many other health and healthcare conditions.Next, we compared the 2021 flu vaccination coverage data with more state demographic information, particular socioeconomic factors like income, population composition, and education attainment. From here, we found a very important factor that is highly correlated to flu coverage rate, which is the high school education attainment rate. Finally, we plotted the flu vaccination coverage data with COVID-19 cases data and found nearly no correlation between them, which is a little bit surprising to us. Initially we hypothesized that the pandemic can potentially increase the flu vaccination rate due to mandates and higher vigilance to personal health.

Admittedly, there are limitations to our project. First, there are data limitations. In aggregating many data sources, we ultimately had to combine variables that may or may not have been collected differently, had different time frames, and used different metrics. In a research project where precision is important, this data acquisition process might need to be tweaked and standardized. Additionally, in doing the age group analysis, we should make the age bins more or less equal, but the source does not allow us to do this. Second, there are project size limitations. We can add more features in multidimensional analysis (biplots), but even if we included only 3 datasets for that part, it exceeds the recommended dataset amount (about 2). 

We also learned a lot about the data visualization process from this project. Obviously, we consolidated our coding abilities in R. We also consolidated our sense of what is a "good" graph for a reader, such as acknowledging the color theme and variable ordering. In a more general sense, we became more careful in examining datasets and more experienced in transforming a raw dataset into a clean, "tidy" dataset for plotting. For example, in the beginning, we could not figure out what the "Dimension" means in the flu vaccination coverage dataset from the CDC, so we did not know that the dataset actually includes racial/age categories until one of our teammates pointed it out. 

In the future, we will probably spend more time finding good data sources that suit our needs, and we will definitely read the column descriptions before working on data cleaning and transformation. We will also try to combine more possible datasets in multidimensional analysis, if possible. We might also like to try arriving at more definitive conclusions and reasons as to why coverage rates differ heavily by state, race, and age. This might include bringing in more census data and incorporating sociopolitical studies.
