# Proposal

## Research topic
Influenza (flu) is a contagious respiratory illness caused by influenza viruses that infect the nose, throat, and lungs. In the United States, millions of people contract the flu every year, and a significant number of people die from this disease despite free access to the vaccine. In our research project, we have two aims in regards to flu data.
We would first like to establish a background on vaccination coverage rates across the United States, particularly how certain states or regions vary. In combining this with census data, we hope to gain insight into how socioeconomic and demographic factors contribute to these flu statistics. Factors of interest include education, household income, poverty level, and race/age/gender pyramids. We will utilize a variety of geographic map plotting as well as biplot and Cleveland dot plots.
 
The second aim of our research project is to assess the impact that the COVID-19 pandemic had on vaccination coverage of the flu, considering the social and political tension surrounding the mandatory vaccination. Perhaps the pandemic also affected mortality rates, either due to vaccine hesitancy or confusing flu for COVID-19 or vice versa. We plan to use a variety of time series visualizations to compare pre-2020 (pandemic start year) levels to post-2020. While this aim is not the primary motivation of our project, introducing these time series analyses adds another dimension to our research.
 
Overall, we aim to get a better understanding about the flu vaccination coverage in the United States. By using a variety of data sources and visualization techniques, we hope to tackle multiple perspectives on the status of the flu in this country.

## Data availability

Since our project topic mainly focuses on influenza vaccination, among all the data sources, the Centers for Disease Control and Prevention (CDC) is one of the most authoritative organizations to gather data. The first dataset we plan to use is the influenza vaccination coverage rates for individuals that are six months or older, provided by the National Center for Immunization and Respiratory Diseases (NCIRD). Here is some information about this dataset:

Dataset source URL: [CDC](https://data.cdc.gov/Flu-Vaccinations/Influenza-Vaccination-Coverage-for-All-Ages-6-Mont/vh55-3he6)

Dataset name: Influenza Vaccination Coverage for All Ages (6+ Months)

Provider and Owner: National Center for Immunization and Respiratory Diseases (NCIRD)

Last Updated: October 18, 2022

The data is collected from the National Immunization Survey-Flu (NIS-Flu), a national wide survey on vaccination coverage conducted by phone, and the Behavioral Risk Factor Surveillance System, another telephone survey. The dataset is recently updated, but the frequency of updates is not clear based on the website. The dataset contains 186,000 records and is organized into 11 columns, including vaccination type, locations of records, time of records, estimates of vaccine coverage, confidence intervals of estimates, etc. According to the website and our own observation, there may be issues regarding the reliability of coverage estimates because sample sizes are sometimes small. The dataset is available in CSV format, importing it into RStudio is straightforward via download and reading. In case there is a need to contact the provider, we can do it directly on the CDC website by sending the provider a message. 

The second set of datasets we will utilize is national census population and demographics data, including population, gender, education levels, income, etc., by state, which will help discover relationships between influenza vaccination and demographics. Here is some information about this dataset:
Dataset source URLs:

1.[Census.gov](https://data.census.gov/cedsci/table?q=population&g=0100000US,%2404000%24001,%240400000&tid=ACSST1Y2021.S0101)  (Population, Age, Gender)

2.[Census.gov](https://data.census.gov/cedsci/table?g=0100000US,%2404000%24001,%240400000&tid=ACSST1Y2019.S1501&tp=true) (Education Attainment)

3.[Census.gov](https://data.census.gov/cedsci/table?q=income&g=0100000US%240400000) (Income)

Provider and Owner: United States Census Bureau

Update Frequency: 1 year

The data is collected by the American Community Survey which is updated annually so that we can observe patterns in any given year or patterns growing across years. The most recent update to the data was 2021. Some potential issues with the datasets are that some margins of error are somewhat wide when doing estimations, and some cells of the dataset are missing which could cause problems when we do data cleaning. These datasets are all available to download in CSV format so that we can directly import them into R, allowing us to combine these demographic data and plot them easily. If there is a question, we can contact the owner by [Census.gov](census.data@census.gov).

The third and final dataset we plan to introduce is a COVID-19 cases dataset. The intention is to see the impact of COVID on flu vaccination coverages, starting from 2020. Therefore, CDC is again the best choice when looking for health and COVID-related datasets. The dataset we chose focuses on the number of cases and deaths caused by COVID by state/region in a time series format. Here is some information about the dataset:

Dataset source URL: [CDC](https://data.cdc.gov/Case-Surveillance/United-States-COVID-19-Cases-and-Deaths-by-State-o/9mfq-cb36)

Dataset name: United States COVID-19 Cases and Deaths by State over Time 

Provider and Owner: CDC COVID-19 Response

Last Updated: October 20, 2022

This data is collected from local reports. Although this dataset is recently updated, it is archived since CDC decided to stop tracking cases and deaths daily. However, it is enough for our analyses, since we are observing past trends. The dataset contains 60,100 rows and 15 columns. Each row represents the total number of confirmed cases, deaths, probable cases, and other information in a state/region at a given time. According to CDC, it is not possible to gather the exact number of cases or deaths. Therefore, the numbers in this dataset are more or less an estimation. The dataset is available in CSV format. We can directly import it into R and combine it with other datasets since the state/region information is clearly marked in this dataset. In case we have a question, we can send the owner a message on CDC’s website.